-- Migration 000044 Rollback
DROP TABLE IF EXISTS usuario_setores CASCADE;
DROP TABLE IF EXISTS usuario_localidades CASCADE;
DROP TABLE IF EXISTS usuario_perfis CASCADE;
DROP TABLE IF EXISTS perfis CASCADE;
DROP TABLE IF EXISTS setores CASCADE;
DROP TABLE IF EXISTS localidades CASCADE;
