-- 1. Atualizar Branding do Sistema
UPDATE system_branding SET
  app_name = 'Assistência Social',
  app_description = 'Secretaria Municipal de Promoção e Assistência Social (SEMPRAS)',
  org_name = 'Prefeitura Municipal de Rondonópolis',
  support_email = 'assistenciasocial@rondonopolis.mt.gov.br',
  support_phone = '(66) 3411-5000',
  support_hours = 'Segunda a Sexta, das 07h às 17h',
  updated_at = NOW();

-- 2. Limpar os serviços antigos de TI
DELETE FROM catalog_services;

-- 3. Inserir os Itens e Serviços Oficiais da Assistência Social (SEMPRAS)
INSERT INTO catalog_services (
  slug, name, summary, category, icon, tagline, description,
  meta_title, meta_description,
  responsibilities, steps, feature_groups, faqs, gallery,
  status, display_order, published_at
) VALUES
(
  'cras',
  'CRAS — Centro de Referência de Assistência Social',
  'Porta de entrada dos serviços socioassistenciais municipais, inscrição e atualização do Cadastro Único, Programa Bolsa Família e fortalecimento de vínculos familiares.',
  'Proteção Básica',
  'Users',
  'Acolhimento, orientação e fortalecimento de laços familiares e comunitários.',
  'O Centro de Referência de Assistência Social (CRAS) é a principal porta de entrada da rede socioassistencial de Rondonópolis. Desenvolve o Serviço de Proteção e Atendimento Integral à Família (PAIF), oferece oficinas, grupos de convivência e orientação direta para acesso a programas sociais.',
  'CRAS — Assistência Social Rondonópolis',
  'Unidades do CRAS em Rondonópolis para atendimento à família, CadÚnico e proteção básica.',
  '[{"side": "provider", "text": "Acolhimento e escuta qualificada por equipe multidisciplinar (assistentes sociais e psicólogos)"}, {"side": "provider", "text": "Inscrição e atualização no Cadastro Único (CadÚnico)"}, {"side": "provider", "text": "Encaminhamento para o Programa Bolsa Família e Tarifa Social"}, {"side": "client", "text": "Comparecer à unidade de referência do seu bairro com documentos pessoais e comprovante de endereço"}, {"side": "client", "text": "Manter os dados do Cadastro Único atualizados a cada 2 anos"}]'::jsonb,
  '[{"number": "01", "title": "Localize o CRAS do seu bairro", "description": "Rondonópolis conta com 9 unidades distribuídas estrategicamente para atender todas as regiões."}, {"number": "02", "title": "Acolhimento Inicial", "description": "Recepção com assistente social para avaliação da situação familiar e identificação das necessidades."}, {"number": "03", "title": "Inclusão em Programas e Benefícios", "description": "Cadastramento ou atualização no CadÚnico e encaminhamento para serviços socioassistenciais."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Quem pode ser atendido no CRAS?", "answer": "Qualquer família ou cidadão em situação de vulnerabilidade social, especialmente beneficiários de programas de transferência de renda e inscritos no Cadastro Único."}, {"question": "Quais documentos levar para o CadÚnico?", "answer": "CPF, RG, Certidão de Nascimento ou Casamento, Título de Eleitor, Carteira de Trabalho de todos os membros da família e comprovante de residência atualizado."}]'::jsonb,
  '[]'::jsonb,
  'published',
  1,
  NOW()
),
(
  'creas',
  'CREAS — Proteção Social Especial',
  'Atendimento especializado e continuado a famílias e indivíduos que vivenciam situações de ameaça ou violações de direitos (PAEFI e medidas socioeducativas).',
  'Média Complexidade',
  'ShieldCheck',
  'Apoio especializado para superação de violências e restauração de direitos.',
  'O Centro de Referência Especializado de Assistência Social (CREAS) atende pessoas e famílias vítimas de violência física, psicológica, negligência, abuso ou exploração sexual, além de acompanhar o cumprimento de medidas socioeducativas em meio aberto.',
  'CREAS — Assistência Social Rondonópolis',
  'Atendimento especializado para famílias em situação de violência ou violação de direitos.',
  '[{"side": "provider", "text": "Acompanhamento psicossocial continuado (PAEFI)"}, {"side": "provider", "text": "Articulação com a rede judiciária, Ministério Público e Saúde"}, {"side": "provider", "text": "Supervisão e acompanhamento de medidas socioeducativas (LA e PSC)"}, {"side": "client", "text": "Comparecer aos atendimentos agendados com a equipe técnica"}, {"side": "client", "text": "Participar das orientações e intervenções familiares propostas"}]'::jsonb,
  '[{"number": "01", "title": "Acolhimento ou Encaminhamento", "description": "O cidadão pode procurar diretamente o CREAS ou ser encaminhado por órgãos de defesa (Conselho Tutelar, Judiciário)."}, {"number": "02", "title": "Plano de Acompanhamento Familiar", "description": "Construção de plano conjunto para superação da situação de violência ou risco vivenciada."}, {"number": "03", "title": "Acompanhamento e Resolução", "description": "Sessões periódicas de apoio psicossocial e reintegração comunitária."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Qual a diferença entre CRAS e CREAS?", "answer": "O CRAS atua na prevenção e na proteção básica (CadÚnico, PAIF). O CREAS atua quando o direito já foi violado (violência, abuso, negligência, cumprimento de medidas socioeducativas)."}]'::jsonb,
  '[]'::jsonb,
  'published',
  2,
  NOW()
),
(
  'centro-pop',
  'Centro POP & Equipe de Abordagem Social',
  'Espaço diurno de acolhimento, higienização, alimentação e apoio para reconstrução da autonomia e reinserção social da população em situação de rua.',
  'População de Rua',
  'Building2',
  'Dignidade, acolhimento e novas oportunidades para quem vive na rua.',
  'O Centro POP funciona de portas abertas para atender pessoas adultas em situação de rua. Oferece espaço de guarda de pertences, higiene pessoal, alimentação, regularização de documentos civis e reinserção ao mercado de trabalho e aos vínculos familiares.',
  'Centro POP — Assistência Social Rondonópolis',
  'Acolhimento diurno e abordagem social para pessoas em situação de rua.',
  '[{"side": "provider", "text": "Alimentação balanceada e espaço para higiene pessoal e lavagem de roupas"}, {"side": "provider", "text": "Equipe de Abordagem Social nas ruas para busca ativa e convencimento"}, {"side": "provider", "text": "Emissão gratuita de documentos (Certidão, RG, CPF)"}, {"side": "client", "text": "Respeitar as regras de convivência e coletividade do espaço"}]'::jsonb,
  '[{"number": "01", "title": "Chegada ou Abordagem", "description": "Por busca espontânea do cidadão ou abordagem humanizada pela equipe móvel da SEMPRAS nas ruas."}, {"number": "02", "title": "Atendimento Social", "description": "Escuta individual, levantamento de necessidades e regularização cadastral e documental."}, {"number": "03", "title": "Encaminhamento", "description": "Acesso a abrigamento, cursos de capacitação, tratamento de saúde ou retorno familiar."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "O Centro POP é um dormitório?", "answer": "Não. O Centro POP é de atendimento diurno. Para pernoite e acolhimento noturno, os usuários são encaminhados para unidades de acolhimento institucional e casas parceiras."}]'::jsonb,
  '[]'::jsonb,
  'published',
  3,
  NOW()
),
(
  'casa-da-mulher',
  'Casa da Mulher — Enfrentamento à Violência',
  'Acolhimento humanizado, proteção e orientação multidisciplinar para mulheres em situação de violência doméstica e familiar.',
  'Proteção à Mulher',
  'Shield',
  'Lugar seguro de proteção, resgate da dignidade e recomeço.',
  'A Casa da Mulher oferece atendimento integrado e articulado com os órgãos de segurança e justiça, garantindo apoio psicológico, social e orientação para medidas protetivas de urgência.',
  'Casa da Mulher — Rondonópolis',
  'Acolhimento e suporte para mulheres vítimas de violência.',
  '[{"side": "provider", "text": "Atendimento reservado e sigiloso por equipe feminina especializada"}, {"side": "provider", "text": "Orientações sobre solicitação e monitoramento de Medidas Protetivas de Urgência"}, {"side": "provider", "text": "Oficinas de capacitação para autonomia financeira e empoderamento"}, {"side": "client", "text": "Procurar a unidade ou ligar nos canais de atendimento para orientação imediata"}]'::jsonb,
  '[{"number": "01", "title": "Atendimento Imediato", "description": "Recepção com acolhimento seguro e sigiloso sem necessidade de agendamento prévio."}, {"number": "02", "title": "Plano de Segurança", "description": "Definição de medidas para proteção da mulher e de seus filhos."}, {"number": "03", "title": "Acompanhamento Multidisciplinar", "description": "Apoio contínuo nas áreas de psicologia, serviço social e encaminhamentos jurídicos."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "O atendimento é confidencial?", "answer": "Sim. Todas as informações e atendimentos são rigorosamente sigilosos e protegidos pela LGPD e pela Lei Maria da Penha."}]'::jsonb,
  '[]'::jsonb,
  'published',
  4,
  NOW()
),
(
  'cadunico-bolsa-familia',
  'Cadastro Único & Programa Bolsa Família',
  'Inscrição e atualização de dados socioeconômicos que garantem o acesso a mais de 30 programas sociais dos governos Federal, Estadual e Municipal.',
  'Transferência de Renda',
  'FileText',
  'Acesso aos programas sociais que transformam realidades.',
  'O Cadastro Único é a ferramenta primordial para mapear as vulnerabilidades e garantir benefícios como o Bolsa Família, Benefício de Prestação Continuada (BPC), Tarifa Social de Energia Elétrica e isenção de taxas em concursos públicos.',
  'Cadastro Único e Bolsa Família — SEMPRAS',
  'Gestão do CadÚnico e benefícios de transferência de renda em Rondonópolis.',
  '[{"side": "provider", "text": "Entrevista e inserção dos dados socioeconômicos no sistema nacional"}, {"side": "provider", "text": "Emissão de comprovante de inscrição e Folha Resumo do CadÚnico"}, {"side": "provider", "text": "Acompanhamento das condicionalidades de saúde e educação"}, {"side": "client", "text": "Apresentar documentos de todos que moram na residência"}, {"side": "client", "text": "Informar qualquer alteração de renda, endereço ou composição familiar"}]'::jsonb,
  '[{"number": "01", "title": "Agendamento ou Atendimento no CRAS", "description": "Procure o CRAS do seu território com a documentação da família."}, {"number": "02", "title": "Entrevista Cadastral", "description": "Preenchimento completo do formulário com todas as fontes de renda e despesas da residência."}, {"number": "03", "title": "Geração do NIS", "description": "Atribuição do Número de Identificação Social (NIS) para cada membro da família."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Quando devo atualizar o Cadastro Único?", "answer": "A cada 2 anos obrigatoriamente, ou sempre que houver mudança de endereço, nascimento, falecimento, casamento ou alteração de renda na família."}]'::jsonb,
  '[]'::jsonb,
  'published',
  5,
  NOW()
),
(
  'beneficios-eventuais',
  'Benefícios Eventuais e Auxílios Emergenciais',
  'Concessão suplementar de auxílio natalidade, auxílio funeral, cestas de alimentos e apoio emergencial a famílias em desabrigo ou vulnerabilidade transitória.',
  'Assistência Emergencial',
  'Package',
  'Apoio tempestivo em momentos imprevistos e situações de perda ou emergência.',
  'Os Benefícios Eventuais são direitos assegurados pela Lei Orgânica da Assistência Social (LOAS) para atender necessidades urgentes decorrentes de contingências sociais, calamidades públicas e momentos de vulnerabilidade temporária.',
  'Benefícios Eventuais — SEMPRAS',
  'Solicitação de auxílios e benefícios eventuais da assistência social.',
  '[{"side": "provider", "text": "Avaliação socioeconômica célere para atendimento imediato da emergência"}, {"side": "provider", "text": "Entrega de cestas de alimentos balanceadas para famílias em extrema vulnerabilidade"}, {"side": "provider", "text": "Concessão e custeio de serviços funerários e auxílio natalidade para mães vulneráveis"}, {"side": "client", "text": "Apresentar comprovação da situação de contingência ou emergência no CRAS mais próximo"}]'::jsonb,
  '[{"number": "01", "title": "Solicitação no CRAS", "description": "Comunicação do fato gerador (nascimento, falecimento, perda de bens por enchente/fogo)."}, {"number": "02", "title": "Parecer Social", "description": "Elaboração de parecer técnico pelo assistente social de plantão."}, {"number": "03", "title": "Liberação do Benefício", "description": "Disponibilização do auxílio financeiro ou material com prioridade máxima."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Quem tem direito aos Benefícios Eventuais?", "answer": "Famílias residentes em Rondonópolis com renda per capita de até meio salário mínimo que estejam vivenciando contingências graves ou imprevistos."}]'::jsonb,
  '[]'::jsonb,
  'published',
  6,
  NOW()
),
(
  'conselho-tutelar',
  'Conselho Tutelar (Central e Vila Operária)',
  'Órgão autônomo e permanente encarregado pela sociedade de zelar pela garantia e defesa efetiva dos direitos da criança e do adolescente.',
  'Garantia de Direitos',
  'KeyRound',
  'Defesa integral e incondicional da infância e da juventude.',
  'O Conselho Tutelar atua com autonomia para requisitar serviços públicos de saúde, educação e assistência, aplicar medidas de proteção a crianças e adolescentes cujos direitos forem ameaçados ou violados e assessorar o Poder Executivo na elaboração orçamentária.',
  'Conselho Tutelar — Rondonópolis',
  'Plantão e atendimento do Conselho Tutelar em Rondonópolis.',
  '[{"side": "provider", "text": "Atendimento e fiscalização 24 horas por dia, 7 dias por semana (inclusive plantões)"}, {"side": "provider", "text": "Aplicação de medidas protetivas previstas no Estatuto da Criança e do Adolescente (ECA)"}, {"side": "provider", "text": "Notificação ao Ministério Público e Justiça da Infância e Juventude em casos graves"}, {"side": "client", "text": "Denunciar qualquer suspeita de maus-tratos, evasão escolar, abuso ou negligência infantil"}]'::jsonb,
  '[{"number": "01", "title": "Recebimento da Demanda", "description": "Via Disque 100, denúncia presencial, contato telefônico ou notificação de escolas/postos de saúde."}, {"number": "02", "title": "Apuração dos Fatos", "description": "Diligência in loco por conselheiros tutelares para verificar as condições de segurança da criança."}, {"number": "03", "title": "Medidas de Proteção", "description": "Encaminhamento aos serviços necessários e acompanhamento contínuo da família."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Como acionar o Conselho Tutelar em fins de semana?", "answer": "Ambos os conselhos (Central e Vila Operária) mantêm escala permanente de plantão telefônico 24 horas para ocorrências urgentes."}]'::jsonb,
  '[]'::jsonb,
  'published',
  7,
  NOW()
),
(
  'scfv',
  'SCFV — Serviço de Convivência e Fortalecimento de Vínculos',
  'Atividades artísticas, esportivas, lúdicas e culturais para crianças, adolescentes e grupos da melhor idade nas unidades de convivência (Padre Lothar, Vila Olímpica).',
  'Convivência',
  'Users',
  'Aprender, conviver e transformar o futuro em comunidade.',
  'O SCFV é um serviço continuado complementar às ações da família e do CRAS. Por meio de oficinas em grupo, estimula o protagonismo juvenil, o desenvolvimento de potencialidades e previne a institucionalização e a segregação comunitária.',
  'SCFV — Convivência e Cidadania',
  'Oficinas e atividades do Serviço de Convivência em Rondonópolis.',
  '[{"side": "provider", "text": "Oficinas regulares de música, artes, dança, esportes e inclusão digital"}, {"side": "provider", "text": "Grupos de socialização e dinâmicas intergeracionais com pessoas idosas"}, {"side": "provider", "text": "Alimentação saudável durante as atividades no contra-turno escolar"}, {"side": "client", "text": "Realizar inscrição no CRAS de referência com apresentação do comprovante de matrícula escolar"}]'::jsonb,
  '[{"number": "01", "title": "Inscrição no CRAS", "description": "Famílias acompanhadas manifestam interesse em matricular crianças, adolescentes ou idosos."}, {"number": "02", "title": "Inserção no Grupo", "description": "Distribuição por faixa etária nos polos de atendimento (ex.: Padre Lothar, Vila Olímpica)."}, {"number": "03", "title": "Participação Contínua", "description": "Frequência nas oficinas e participação em mostras culturais e eventos comunitários."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "O SCFV substitui a escola?", "answer": "Não. O SCFV funciona no contra-turno escolar e tem como exigência a matrícula e a frequência escolar regular da criança ou jovem."}]'::jsonb,
  '[]'::jsonb,
  'published',
  8,
  NOW()
),
(
  'casa-abrigo',
  'Casa Abrigo Municipal',
  'Unidade pública de acolhimento institucional provisório e excepcional para crianças e adolescentes em situação de risco pessoal e social.',
  'Alta Complexidade',
  'Building2',
  'Ambiente acolhedor e proteção integral até a reintegração familiar.',
  'A Casa Abrigo funciona 24 horas por dia com estrutura residencial privativa, garantindo alimentação, vestuário, atendimento médico, psicológico e escolar, preservando os direitos individuais de cada criança enquanto sua situação jurídica é acompanhada pela Justiça da Infância.',
  'Casa Abrigo — Assistência Social Rondonópolis',
  'Acolhimento institucional provisório em Rondonópolis.',
  '[{"side": "provider", "text": "Acolhimento imediato 24 horas mediante determinação judicial ou do Conselho Tutelar"}, {"side": "provider", "text": "Equipe de cuidadores capacitados, assistentes sociais e apoio psicológico contínuo"}, {"side": "provider", "text": "Garantia de matrícula escolar e cuidados integrais de saúde"}, {"side": "client", "text": "Acesso restrito determinado pela autoridade judicial competente"}]'::jsonb,
  '[{"number": "01", "title": "Determinação da Medida", "description": "Determinação judicial ou aplicação emergencial por autoridade competente diante de risco grave comprovado."}, {"number": "02", "title": "Acolhimento Residencial", "description": "Recepção carinhosa e inserção na rotina saudável da unidade de abrigo."}, {"number": "03", "title": "Trabalho de Reintegração", "description": "Esforço técnico contínuo para retorno seguro à família biológica ou extensão familiar."}]'::jsonb,
  '[]'::jsonb,
  '[{"question": "Qualquer pessoa pode visitar a Casa Abrigo?", "answer": "Não. Por determinação do ECA e da Vara da Infância e Juventude, o endereço e as visitas são restritos e controlados para proteger a segurança das crianças acolhidas."}]'::jsonb,
  '[]'::jsonb,
  'published',
  9,
  NOW()
);
